baseURL = 'https://example.org/'
# baseURL = 'https://www.ceusdosul.net/qr/'
languageCode = 'pt-pt'
title = 'Questão Repetida'
theme = 'qr-theme'
contentDir = 'content'

[security]
  enableInlineShortcodes = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  facebook = 'https://facebook.com/questao.repetida'
  instagram = 'https://instagram.com/questao.repetida'
  whatsapp = 'https://wa.me/351932399639'


[menus]
  [[menus.main]]
    name = 'HOME'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'NÓS'
    pageRef = '/nos'
    weight = 20

  [[menus.main]]
    name = 'AGENDA'
    pageRef = '/agenda'
    weight = 30

  [[menus.main]]
    name = "CIRCULAÇÃO"
    identifier = 'circ'
    pageRef = '/circulacao'
    weight = 40

  [[menus.main]]
    name = 'PROJECTOS'
    identifier = 'projectos'
    pageRef = '/projectos'
    weight = 50

#  [[menus.main]]
#    name = 'TEATRO'
#    parent = 'projectos'
#    pageRef = '/projectos/teatro'
#    weight = 110
#
#  [[menus.main]]
#    name = 'MÚSICA'
#    parent = 'projectos'
#    pageRef = '/projectos/musica'
#    weight = 120
#
#  [[menus.main]]
#    name = 'ARTES VISUAIS'
#    parent = 'projectos'
#    pageRef = '/projectos/artesvisuais'
#    weight = 130
#
#  [[menus.main]]
#    name = 'MULTIDISCIPLINAR'
#    parent = 'projectos'
#    pageRef = '/projectos/multidisciplinar'
#    weight = 140
#  
#  [[menus.main]]
#    name = 'ARTE-SOCIAL'
#    parent = 'projectos'
#    pageRef = '/projectos/artesocial'
#    weight = 150
#



